//
// "$Id: fl_message.H 8864 2011-07-19 04:49:30Z greg.ercolano $"
//
// Standard message header file for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2010 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

#include "fl_ask.H"

//
// End of "$Id: fl_message.H 8864 2011-07-19 04:49:30Z greg.ercolano $".
//
