//
// "$Id: Fl_Toggle_Round_Button.H 8864 2011-07-19 04:49:30Z greg.ercolano $"
//
// Toggle round button header file for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2010 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     http://www.fltk.org/COPYING.php
//
// Please report all bugs and problems on the following page:
//
//     http://www.fltk.org/str.php
//

// provided for back-compatibility only

#ifndef Fl_Toggle_Round_Button
#include "Fl_Round_Button.H"
#define Fl_Toggle_Round_Button Fl_Round_Button
#endif

//
// End of "$Id: Fl_Toggle_Round_Button.H 8864 2011-07-19 04:49:30Z greg.ercolano $".
//
